### post bank
POST http://localhost/api/bank
Content-Type: application/json

{
    "_id":"{{mcm2_norek}}",
    "service":"mcm2",
    "corp_id":"{{mcm2_corp_id}}",
    "user_id":"{{mcm2_user_id}}",
    "password":"{{mcm2_password}}",
    "interval":300000,
    "auto_start":1,
    "norek":"{{mcm2_norek}}"
}

### get bank
GET http://localhost/api/bank

### patch bank
PATCH http://localhost/api/bank?_id={{mcm2_norek}}
Content-Type: application/json

{
    "_id":"{{mcm2_norek}}",
    "service":"mcm2",
    "corp_id":"{{mcm2_corp_id}}",
    "user_id":"{{mcm2_user_id}}",
    "password":"{{mcm2_password}}",
    "interval":300000,
    "auto_start":0,
    "norek":"{{mcm2_norek}}"
}

### delete bank
DELETE http://localhost/api/bank?_id={{mcm2_norek}}

### post bank/data_bank
POST http://localhost/api/bank/data_bank
Content-Type: application/json

{
}

### get bank/data_bank
GET http://localhost/api/bank/data_bank?tanggal_awal=2023-06-01&tanggal_akhir=2023-06-31&limit=20&page=1

### patch bank/data_bank
PATCH http://localhost/api/bank/data_bank?kode={{mcm2_norek}}
Content-Type: application/json

{
}

### delete bank/data_bank
DELETE http://localhost/api/bank/data_bank?kode={{mcm2_norek}}






### login
GET http://localhost/api/bank/login?_id={{mcm2_norek}}

### logout
GET http://localhost/api/bank/logout?_id={{mcm2_norek}}

### mutasi
GET http://localhost/api/bank/mutasi
?_id={{mcm2_norek}}
&tanggal_awal=2023-05-01
&tanggal_akhir=2023-05-31