### signin
POST http://localhost/api/auth/signin
Content-Type: application/json

{
    "username":""
}


### signup
POST http://localhost/api/auth/signup
Content-Type: application/json

{
    "username":""
}


### challenge
POST http://localhost/api/auth/challenge
Content-Type: application/json

{
    "username":"",
    "password":""
}


### signout
GET http://localhost/api/auth/signout



### refresh
GET http://localhost/api/auth/refresh


