### Login
POST http://103.184.122.10/api/auth/signin
Content-Type: application/json

{
    "username":"+6285793712632"
}


### Register
POST http://103.184.122.10/api/auth/signup
Content-Type: application/json

{
    "username":"+6285793712632"
}


### Confirm
POST http://103.184.122.10/api/auth/challenge
Content-Type: application/json

{
    "username":"+6285793712632",
    "password":"235958"
}


### Logout
GET http://103.184.122.10/api/auth/signout

### Logout
GET http://103.184.122.10/api/auth/signout
Authorization: Bearer {{access_token}}



### Refresh Token
GET http://103.184.122.10/api/auth/refresh

### Refresh Token
GET http://103.184.122.10/api/auth/refresh
Authorization: Bearer {{refresh_token}}