
### Buat konfigurasi baru
POST https://localhost/api/bank
Content-Type: application/json

{
    "norek":"{{bnidirect_norek}}",
    "tipe":"bnidirect",
    "corp_id":"{{bnidirect_corp_id}}",
    "user_id":"{{bnidirect_user_id}}",
    "password":"{{bnidirect_password}}",
    "interval":300000,
    "auto_start":0
}

### Ambil semua konfigurasi
GET https://localhost/api/bank

### Lihat Konfigurasi
GET https://localhost/api/bank?norek={{bnidirect_norek}}

### Ubah konfigurasi
PATCH https://localhost/api/bank?norek={{bnidirect_norek}}
Content-Type: application/json

{
    "norek":"{{bnidirect_norek}}",
    "tipe":"bnidirect",
    "corp_id":"{{bnidirect_corp_id}}",
    "user_id":"{{bnidirect_user_id}}",
    "password":"{{bnidirect_password}}",
    "interval":300000,
    "auto_start":1
}

### Hapus konfigurasi
DELETE https://localhost/api/bank?norek={{bnidirect_norek}}






### Lihat semua data bank
GET https://localhost/api/bank/data-bank
?tanggal_awal=2023-06-01
&tanggal_akhir=2023-06-30
&bank=
&no_rekening=
&limit=20
&page=1


### Hapus data bank
DELETE https://localhost/api/bank/data-bank?kode=







### Login
GET https://localhost/api/bank/login?norek={{bnidirect_norek}}

### Logout
GET https://localhost/api/bank/logout?norek={{bnidirect_norek}}

### Mutasi
GET https://localhost/api/bank/mutasi
?norek={{bnidirect_norek}}
&page=1
&tanggal_awal=2023-05-01
&tanggal_akhir=2023-05-30