### Buat konfigurasi bank baru
POST http://localhost/api/bank
Content-Type: application/json

{
    "_id":"{{bnidirect_norek}}",
    "service":"bnidirect",
    "corp_id":"{{bnidirect_corp_id}}",
    "user_id":"{{bnidirect_user_id}}",
    "password":"{{bnidirect_password}}",
    "interval":300000,
    "auto_start":1,
    "norek":"{{bnidirect_norek}}"
}

### Lihat Konfigurasi Bank
GET http://localhost/api/bank

### Ubah konfigurasi bank
PATCH http://localhost/api/bank?_id={{bnidirect_norek}}
Content-Type: application/json

{
    "_id":"{{bnidirect_norek}}",
    "service":"bnidirect",
    "corp_id":"{{bnidirect_corp_id}}",
    "user_id":"{{bnidirect_user_id}}",
    "password":"{{bnidirect_password}}",
    "interval":300000,
    "auto_start":0,
    "norek":"{{bnidirect_norek}}"
}

### Hapus konfigurasi bank
DELETE http://localhost/api/bank?_id={{bnidirect_norek}}

### Lihat mutasi bank yang disimpan
GET http://localhost/api/bank/data_bank?tanggal_awal=2023-06-01&tanggal_akhir=2023-06-31&limit=20&page=1&bank=BNI&no_rekening=

### Masuk/Login dengan konfigurasi yang disimpan
GET http://localhost/api/bank/login?_id={{bnidirect_norek}}

### Keluar/Logout
GET http://localhost/api/bank/logout?_id={{bnidirect_norek}}

### Lihat mutasi bank
GET http://localhost/api/bank/mutasi?_id={{bnidirect_norek}}&tanggal_awal=2023-05-01&tanggal_akhir=2023-05-31