### Buat konfigurasi bank baru
POST http://localhost/api/bank
Content-Type: application/json

{
    "_id":"{{ibank_norek}}",
    "service":"ibank",
    "corp_id":"{{ibank_corp_id}}",
    "user_id":"{{ibank_user_id}}",
    "password":"{{ibank_password}}",
    "interval":300000,
    "auto_start":1,
    "norek":"{{ibank_norek}}"
}


### Lihat Konfigurasi Bank
GET http://localhost/api/bank

### Ubah konfigurasi bank
PATCH http://localhost/api/bank?_id={{ibank_norek}}
Content-Type: application/json

{
    "_id":"{{ibank_norek}}",
    "service":"ibank",
    "corp_id":"{{ibank_corp_id}}",
    "user_id":"{{ibank_user_id}}",
    "password":"{{ibank_password}}",
    "interval":300000,
    "auto_start":0,
    "norek":"{{ibank_norek}}"
}

### Hapus konfigurasi bank
DELETE http://localhost/api/bank?_id={{ibank_norek}}

### Lihat mutasi bank yang disimpan
GET http://localhost/api/bank/data_bank?tanggal_awal=2023-06-01&tanggal_akhir=2023-06-31&limit=20&page=1

### Masuk/Login dengan konfigurasi yang disimpan
GET http://localhost/api/bank/login?_id={{ibank_norek}}

### Keluar/Logout
GET http://localhost/api/bank/logout?_id={{ibank_norek}}

### Lihat mutasi bank
GET http://localhost/api/bank/mutasi?_id={{ibank_norek}}&tanggal_awal=2023-06-23&tanggal_akhir=2023-06-23