
### Buat konfigurasi baru
POST https://localhost/api/bank
Content-Type: application/json

{
    "norek":"{{ibank_norek}}",
    "tipe":"ibank",
    "corp_id":"{{ibank_corp_id}}",
    "user_id":"{{ibank_user_id}}",
    "password":"{{ibank_password}}",
    "interval":300000,
    "auto_start":0
}

### Ambil semua konfigurasi
GET https://localhost/api/bank

### Lihat Konfigurasi
GET https://localhost/api/bank?norek={{ibank_norek}}

### Ubah konfigurasi
PATCH https://localhost/api/bank?norek={{ibank_norek}}
Content-Type: application/json

{
    "norek":"{{ibank_norek}}",
    "tipe":"ibank",
    "corp_id":"{{ibank_corp_id}}",
    "user_id":"{{ibank_user_id}}",
    "password":"{{ibank_password}}",
    "interval":300000,
    "auto_start":1
}

### Hapus konfigurasi
DELETE https://localhost/api/bank?norek={{ibank_norek}}






### Login
GET https://localhost/api/bank/login?norek={{ibank_norek}}

### Logout
GET https://localhost/api/bank/logout?norek={{ibank_norek}}

### Mutasi
GET https://localhost/api/bank/mutasi
?norek={{ibank_norek}}
&page=1
&tanggal_awal=2023-06-27
&tanggal_akhir=2023-06-27