
###
GET http://localhost/api/kepooh2h/Guest/Product?produk=E

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=G

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=GM

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=I

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=IG

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=PLN

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=PPOB

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=SM

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=S

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=T

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=V

###
GET http://localhost/api/kepooh2h/Guest/Product?produk=X

###
GET http://localhost/api/kepooh2h/Guest/Product
?produk=E
&produk=G
&produk=GM
&produk=I
&produk=IG
&produk=PLN
&produk=PPOB
&produk=SM
&produk=S
&produk=T
&produk=V
&produk=X

