
### Buat konfigurasi baru
POST https://localhost/api/bank
Content-Type: application/json

{
    "norek":"{{mcm2_norek}}",
    "tipe":"mcm2",
    "corp_id":"{{mcm2_corp_id}}",
    "user_id":"{{mcm2_user_id}}",
    "password":"{{mcm2_password}}",
    "interval":300000,
    "auto_start":0
}

### Ambil semua konfigurasi
GET https://localhost/api/bank

### Lihat Konfigurasi
GET https://localhost/api/bank?norek={{mcm2_norek}}

### Ubah konfigurasi
PATCH https://localhost/api/bank?norek={{mcm2_norek}}
Content-Type: application/json

{
    "norek":"{{mcm2_norek}}",
    "tipe":"mcm2",
    "corp_id":"{{mcm2_corp_id}}",
    "user_id":"{{mcm2_user_id}}",
    "password":"{{mcm2_password}}",
    "interval":300000,
    "auto_start":1
}

### Hapus konfigurasi
DELETE https://localhost/api/bank?norek={{mcm2_norek}}






### Login
GET https://localhost/api/bank/login?norek={{mcm2_norek}}

### Logout
GET https://localhost/api/bank/logout?norek={{mcm2_norek}}

### Mutasi
GET https://localhost/api/bank/mutasi
?norek={{mcm2_norek}}
&page=1
&tanggal_awal=2023-05-01
&tanggal_akhir=2023-05-30