
### CONFIG (CALLBACK => SETTING KE OTOMAX)
POST http://localhost/api/mitra-bukalapak/config?stg=1
Content-Type: application/json

{
    "callback": "http://127.0.0.1/api/mitra-bukalapak/debug",
    "scope":[
        "user.wallet-balance.read",
        "transaction.prepaid-electricity-transaction.read",
        "transaction.prepaid-electricity-transaction.write",
        "transaction.e-wallet-transaction.read",
        "transaction.e-wallet-transaction.write",
        "transaction.prepaid-phone-transaction.read",
        "transaction.prepaid-phone-transaction.write",
        "transaction.postpaid-electricity-transaction.write",
        "transaction.postpaid-electricity-transaction.read"
    ],
    "basic_token":"username:password",
    "parser":{
        "postpaid_electricity_customer":"data=[customer_name]/[customer_number]/[segmentation]/[power]/[stand_meter]/[outstanding_bill]/[unpaid_bill]/[period.0]/[penalty_fee]/[admin_charge]/[bills.0.period]/[bills.0.penalty_fee]/[bills.0.amount]/[currency]/[total_price] order_id=[order_id] phone_number=[phone_number] serial_number=[serial_number] total_price=[total_price] response_code=[response_code] custom_admin=[custom_admin] custom_tagihan=[custom_tagihan] custom_total=[custom_total] custom_balance=[custom_balance]",
        "default":"order_id=[order_id] phone_number=[phone_number] serial_number=[serial_number] total_price=[total_price] response_code=[response_code] custom_admin=[custom_admin] custom_tagihan=[custom_tagihan] custom_total=[custom_total] custom_balance=[custom_balance]"
    },
    "formula":{
      "postpaid_electricity_customer":{
        "custom_admin":"3000",
        "custom_total":"[custom_admin]+[bills.0.amount]",
        "custom_balance":"[balance]-[total_price]"
      },
      "default":{
        "custom_admin":"0"
      }
    }
}






### CALLBACK (SETTING DI MITRA BUKALAPAK => http://localhost/api/mitra-bukalapak/callback)
POST http://localhost/api/mitra-bukalapak/callback
Content-Type: application/json

[[{"postpaid_electricity_customer": {
    "customer_name": "LANGGAR ALI MUCHTAR",
    "customer_number": "518010582090",
    "segmentation": "R1M",
    "power": 900,
    "stand_meter": "00001629-00001752",
    "outstanding_bill": 1,
    "unpaid_bill": 0,
    "period": [
      "2023-09-01"
    ],
    "penalty_fee": "0",
    "admin_charge": "150",
    "bills": [
      {
        "period": "2023-09-01",
        "penalty_fee": "0",
        "amount": "182926"
      }
    ],
    "currency": "IDR",
    "total_price": "183076",
    "response_code": "0000",
    "message": "successful"
  },"prepaid_electricity_transaction":{"order_id":"12000000009","customer_name":"AHMADI","customer_number":"520000000000","meter_number":"520000000000","token_number":"40129107110371994273","segmentation":"R1M","power":"900","kwh":"13.6","reference_number":"0ASM21VS125496FEEE3ACE3E05D321EB","currency":"IDR","total_price":"50000","token_price":"18348","value_added_tax":"0","public_lighting_tax":"1652","stamp_duty":"0","installment":"0","admin_fee":"500","info":"Informasi Hubungi Call Center 123 Atau hubungi PLN Terdekat ","response_code":"0000","message":"successful"}},{"e_wallet_transaction":{"order_id":"22000000006","phone_number":"081200000000","customer_name":"John Doe","serial_number":"1234567890","currency":"IDR","total_price":"10000","response_code":"0000","message":"successful"}},{"prepaid_phone_transaction":{"order_id":"32000000003","phone_number":"081200000000","serial_number":"1234567890","currency":"IDR","total_price":"10000","response_code":"0000","message":"successful"}}]]

### CALLBACK (SETTING DI MITRA BUKALAPAK => http://localhost/api/mitra-bukalapak/callback)
POST http://localhost/api/mitra-bukalapak/callback
Content-Type: application/json

{"prepaid_phone_transaction":{"order_id":"32000000003","phone_number":"081200000000","serial_number":"1234567890","currency":"IDR","total_price":"10000","response_code":"0000","message":"successful"}}

### CALLBACK (SETTING DI MITRA BUKALAPAK => http://localhost/api/mitra-bukalapak/callback)
POST http://localhost/api/mitra-bukalapak/callback
Content-Type: application/json

{"postpaid_electricity_customer": {
    "customer_name": "LANGGAR ALI MUCHTAR",
    "customer_number": "518010582090",
    "segmentation": "R1M",
    "power": 900,
    "stand_meter": "00001629-00001752",
    "outstanding_bill": 1,
    "unpaid_bill": 0,
    "period": [
      "2023-09-01"
    ],
    "penalty_fee": "0",
    "admin_charge": "150",
    "bills": [
      {
        "period": "2023-09-01",
        "penalty_fee": "0",
        "amount": "182926"
      }
    ],
    "currency": "IDR",
    "total_price": "183076",
    "response_code": "0000",
    "message": "successful"
  }}





### TOKEN
GET http://localhost/api/mitra-bukalapak/token?stg=1






### BALANCE
GET http://localhost/api/mitra-bukalapak/balance?stg=1






### LISTRIK
GET http://localhost/api/mitra-bukalapak/listrik?order_id=&product_code=&customer_number=

### ADVICE_LISTRIK
GET http://localhost/api/mitra-bukalapak/advice_listrik?order_id=

### INQUIRY_LISTRIK
GET http://localhost/api/mitra-bukalapak/inquiry_listrik?product_code=&customer_number=






### PULSA
GET http://localhost/api/mitra-bukalapak/pulsa?order_id=&product_code=&phone_number=

###
GET http://localhost/api/mitra-bukalapak/pulsa?order_id=35345&product_code=tsel100&phone_number=0821312312

### ADVICE_PULSA
GET http://localhost/api/mitra-bukalapak/advice_pulsa?order_id=

### INQUIRY_PULSA
GET http://localhost/api/mitra-bukalapak/inquiry_pulsa?product_code=&phone_number=






### WALLET
GET http://localhost/api/mitra-bukalapak/wallet?order_id=&product_code=&phone_number=

### ADVICE_WALLET
GET http://localhost/api/mitra-bukalapak/advice_wallet?order_id=

### INQUIRY_WALLET
GET http://localhost/api/mitra-bukalapak/inquiry_wallet?product_code=&phone_number=






### LISTRIK_PASCABAYAR
GET http://localhost/api/mitra-bukalapak/listrik_pascabayar?order_id=&product_code=&customer_number=

### ADVICE_LISTRIK_PASCABAYAR
GET http://localhost/api/mitra-bukalapak/advice_listrik_pascabayar?order_id=

### INQUIRY_LISTRIK_PASCABAYAR
GET http://localhost/api/mitra-bukalapak/inquiry_listrik_pascabayar?product_code=&customer_number=
