### Buat konfigurasi center/sender baru
POST http://localhost/api/center
Content-Type: application/json

{
    "_id": "{{telegram_username}}",
    "service": "telegram",
    "username": "{{telegram_username}}",
    "password": "{{telegram_password}}",
    "startup_login": 1,
    "sender_speed": 1000,
    "service_center": 1
}

### Lihat daftar center/sender
GET http://localhost/api/center

### Lihat data center/sender dengan _id
GET http://localhost/api/center?_id={{telegram_username}}

### Ubah konfigurasi center/sender yang disimpan
PATCH http://localhost/api/center?_id={{telegram_username}}
Content-Type: application/json

{
    "_id": "{{telegram_username}}",
    "service": "telegram",
    "username": "{{telegram_username}}",
    "password": "{{telegram_password}}",
    "startup_login": 1,
    "sender_speed": 1000,
    "service_center": 1
}

### Hapus konfigurasi center/sender yang disimpan
DELETE http://localhost/api/center?_id={{telegram_username}}

### Login
GET http://localhost/api/center/login?_id={{telegram_username}}

### Logout
GET http://localhost/api/center/logout?_id={{telegram_username}}

### Kirim pesan
GET http://localhost/api/center/send?_id={{telegram_username}}&penerima=1344008938&pesan=pesan
