
### Buat konfigurasi baru
POST https://localhost/api/center
Content-Type: application/json

{
    "username": "{{whatsapp_username}}",
    "password": "{{whatsapp_password}}",
    "type": "whatsapp",
    "startup_login": 0,
    "sender_speed": 1000,
    "sms_center": 1
}

### Ambil semua konfigurasi
GET https://localhost/api/center

### Lihat Konfigurasi
GET https://localhost/api/center?username={{whatsapp_username}}

### Ubah konfigurasi
PATCH https://localhost/api/center?username={{whatsapp_username}}
Content-Type: application/json

{
    "username": "{{whatsapp_username}}",
    "password": "{{whatsapp_password}}",
    "type": "whatsapp",
    "startup_login": 1,
    "sender_speed": 1000,
    "sms_center": 1
}

### Hapus konfigurasi
DELETE https://localhost/api/center?username={{whatsapp_username}}






### Login
GET https://localhost/api/center/login?username={{whatsapp_username}}

### Logout
GET https://localhost/api/center/logout?username={{whatsapp_username}}

### Mengirim pesan
GET https://localhost/api/center/send
?username={{whatsapp_username}}
&penerima=6281935155404
&pesan=6281935155404