### post center
POST http://localhost/api/center
Content-Type: application/json

{
    "_id": "{{xmpp_username}}",
    "service": "xmpp",
    "username": "{{xmpp_username}}",
    "password": "{{xmpp_password}}",
    "startup_login": 1,
    "sender_speed": 1000,
    "service_center": 1
}

### get center
GET http://localhost/api/center

### get center
GET http://localhost/api/center?_id={{xmpp_username}}

### patch center
PATCH http://localhost/api/center?_id={{xmpp_username}}
Content-Type: application/json

{
    "_id": "{{xmpp_username}}",
    "service": "xmpp",
    "username": "{{xmpp_username}}",
    "password": "{{xmpp_password}}",
    "startup_login": 1,
    "sender_speed": 1000,
    "service_center": 1
}

### delete center
DELETE http://localhost/api/center?_id={{xmpp_username}}






### login
GET http://localhost/api/center/login?_id={{xmpp_username}}

### logout
GET http://localhost/api/center/logout?_id={{xmpp_username}}

### send
GET http://localhost/api/center/send
?_id={{xmpp_username}}
&penerima=connect_client@jabb.im
&pesan=pesan
