
### Buat konfigurasi baru
POST https://localhost/api/center
Content-Type: application/json

{
    "username": "{{xmpp_username}}",
    "password": "{{xmpp_password}}",
    "type": "xmpp",
    "startup_login": 0,
    "sender_speed": 1000,
    "sms_center": 1
}

### Ambil semua konfigurasi
GET https://localhost/api/center

### Lihat Konfigurasi
GET https://localhost/api/center?username={{xmpp_username}}

### Ubah konfigurasi
PATCH https://localhost/api/center?username={{xmpp_username}}
Content-Type: application/json

{
    "username": "{{xmpp_username}}",
    "password": "{{xmpp_password}}",
    "type": "xmpp",
    "startup_login": 1,
    "sender_speed": 1000,
    "sms_center": 1
}

### Hapus konfigurasi
DELETE https://localhost/api/center?username={{xmpp_username}}






### Login
GET https://localhost/api/center/login?username={{xmpp_username}}

### Logout
GET https://localhost/api/center/logout?username={{xmpp_username}}

### Mengirim pesan
GET https://localhost/api/center/send
?username={{xmpp_username}}
&penerima=connect_client@jabb.im
&pesan=connect_client@jabb.im